yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
  "nuxt@^2.14.7":
    dependencies:
      "webpack": "^4.44.2"
  "@nuxt/babel-preset-app@^2.14.7":
    dependencies:
      "core-js-compat": "^3.7.0"
  "@nuxt/core@^2.14.7":
    dependencies:
      "@nuxt/vue-app": "^2.14.7"
      "compression": "^1.7.4"
      "cssnano": "^4.1.10"
      "node-fetch": "^2.6.1"
      "postcss-import": "^12.0.1"
      "postcss-preset-env": "^6.7.0"
      "postcss-url": "^8.0.0"
      "unfetch": "^4.2.0"
      "vue": "^2.6.12"
      "vue-client-only": "^2.0.0"
      "vue-meta": "^2.4.0"
      "vue-no-ssr": "^1.1.1"
      "vue-router": "3.4.8"
      "vue-template-compiler": "^2.6.12"
      "vuex": "^3.5.1"
  "@nuxt/webpack@^2.14.7":
    dependencies:
      "vue-meta": "^2.4.0"
      "vue-template-compiler": "^2.6.12"
